// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sell() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container py-5\"><h1 class=\"text-center mb-4 fw-bold display-5\">Ce vrei să vinzi?</h1><p class=\"text-center mb-5 fs-5 text-muted\">Alege categoria dispozitivului Apple.</p><div class=\"row row-cols-2 row-cols-md-4 g-4 justify-content-center\"><div class=\"col text-center\"><a href=\"/sell/apple/iphone\" class=\"text-decoration-none text-dark\"><div class=\"card shadow-sm border-0 rounded-4 p-3 h-100 hover-scale\"><img src=\"/images/iphone.png\" alt=\"IPhone\" class=\"mx-auto mb-3 img-fluid\" style=\"max-height: 120px; object-fit: contain;\"><h5 class=\"fw-semibold\">IPhone</h5></div></a></div><div class=\"col text-center\"><a href=\"/sell/apple/macbook\" class=\"text-decoration-none text-dark\"><div class=\"card shadow-sm border-0 rounded-4 p-3 h-100 hover-scale\"><img src=\"/images/macbook.png\" alt=\"MacBook\" class=\"mx-auto mb-3 img-fluid\" style=\"max-height: 120px; object-fit: contain;\"><h5 class=\"fw-semibold\">Macbook</h5></div></a></div><div class=\"col text-center\"><a href=\"/sell/apple/ipad\" class=\"text-decoration-none text-dark\"><div class=\"card shadow-sm border-0 rounded-4 p-3 h-100 hover-scale\"><img src=\"/images/ipad.png\" alt=\"IPad\" class=\"mx-auto mb-3 img-fluid\" style=\"max-height: 120px; object-fit: contain;\"><h5 class=\"fw-semibold\">IPad</h5></div></a></div><div class=\"col text-center\"><a href=\"/images/airpods.png\" class=\"text-decoration-none text-dark\"><div class=\"card shadow-sm border-0 rounded-4 p-3 h-100 hover-scale\"><img src=\"/images/airpods.png\" alt=\"Airpods\" class=\"mx-auto mb-3 img-fluid\" style=\"max-height: 120px; object-fit: contain;\"><h5 class=\"fw-semibold\">Airpods</h5></div></a></div></div><style>\n            .hover-scale:hover {\n                transform: scale(1.05);\n                transition: transform 0.2s ease-in-out;\n            }\n        </style></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
