// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar(isLoggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"navbar navbar-expand-lg navbar-dark shadow-sm px-4 py-3 rounded-bottom-4 mx-3 mt-3\" style=\"background: linear-gradient(to left, #fc4a7a, #9675ff, #3bc3ff); border-radius: 2rem;\"><style>\n            .nav-link-custom {\n                font-size: 1.15rem;\n                transition: all 0.2s ease-in-out;\n                display: inline-flex;\n                align-items: center;\n            }\n            .nav-link-custom:hover {\n                transform: scale(1.12);\n                font-weight: 600;\n            }\n        </style><div class=\"container-fluid d-flex justify-content-between align-items-center\"><a class=\"navbar-brand d-flex align-items-center gap-2 fw-bold\" href=\"/\"><img src=\"/images/IMarket2.png\" height=\"60\" class=\"rounded-4 shadow-sm\"></a> <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button><div class=\"collapse navbar-collapse\" id=\"navbarNav\"><ul class=\"navbar-nav ms-auto align-items-center gap-3\"><li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/\">Home</a></li><li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/api/products\">Products</a></li><li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/about\">About</a></li><li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/contact\">Contacts</a></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/logout\">Logout</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"nav-item\"><a class=\"nav-link nav-link-custom active\" href=\"/login\">Login</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ul></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
